import { useMemo, useState } from 'react';
import { Bell, ChevronDown, CircleHelp, Clock3, CreditCard, LayoutDashboard, LogOut, Menu, MoreHorizontal, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, TicketCheck, Users, Wrench, X } from 'lucide-react';
import './styles.css';

type Status = 'New' | 'Assigned' | 'In progress' | 'Resolved';
type Ticket = { id: string; title: string; customer: string; category: string; priority: 'High' | 'Medium' | 'Low'; status: Status; assignee: string; updated: string };
const seed: Ticket[] = [
  { id: 'SR-1048', title: 'VPN access not working', customer: 'Nimbus Systems', category: 'IT Support', priority: 'High', status: 'In progress', assignee: 'Amelia Harper', updated: '12m ago' },
  { id: 'SR-1047', title: 'Quarterly HVAC maintenance', customer: 'Northstar Labs', category: 'Facilities', priority: 'Medium', status: 'Assigned', assignee: 'Daniel Kim', updated: '35m ago' },
  { id: 'SR-1046', title: 'New employee laptop setup', customer: 'Atlas Partners', category: 'Onboarding', priority: 'Low', status: 'New', assignee: 'Unassigned', updated: '1h ago' },
  { id: 'SR-1045', title: 'Invoice correction request', customer: 'Verde Studio', category: 'Billing', priority: 'Medium', status: 'Resolved', assignee: 'Amelia Harper', updated: '2h ago' },
  { id: 'SR-1044', title: 'Conference room display issue', customer: 'Nimbus Systems', category: 'IT Support', priority: 'High', status: 'In progress', assignee: 'Daniel Kim', updated: '3h ago' }
];
const nav = [{ icon: LayoutDashboard, label: 'Overview' }, { icon: TicketCheck, label: 'Service requests' }, { icon: Users, label: 'Customers' }, { icon: Wrench, label: 'Team' }, { icon: CreditCard, label: 'Payments' }];
function Badge({ value, kind }: { value: string; kind?: string }) { return <span className={`badge ${kind || value.toLowerCase().replace(' ', '-')}`}>{value}</span> }
function App() {
  const [tickets, setTickets] = useState(seed); const [active, setActive] = useState('Overview'); const [query, setQuery] = useState(''); const [showCreate, setShowCreate] = useState(false); const [sidebar, setSidebar] = useState(false);
  const visible = useMemo(() => tickets.filter(t => `${t.id} ${t.title} ${t.customer}`.toLowerCase().includes(query.toLowerCase())), [tickets, query]);
  const addTicket = (form: HTMLFormElement) => { const data = new FormData(form); const title = String(data.get('title') || '').trim(); if (!title) return; setTickets([{ id: `SR-${1049 + tickets.length}`, title, customer: String(data.get('customer') || 'New customer'), category: String(data.get('category') || 'General'), priority: 'Medium', status: 'New', assignee: 'Unassigned', updated: 'Just now' }, ...tickets]); setShowCreate(false); };
  return <div className="shell">
    <aside className={sidebar ? 'open' : ''}><div className="brand"><div className="brand-mark">S</div><span>service<span>hub</span></span><button className="mobile-close" onClick={() => setSidebar(false)}><X /></button></div><div className="workspace"><small>WORKSPACE</small><button>Acme Corporation <ChevronDown size={15}/></button></div><nav>{nav.map(({ icon: Icon, label }) => <button key={label} className={active === label ? 'selected' : ''} onClick={() => { setActive(label); setSidebar(false); }}><Icon size={18}/>{label}{label === 'Service requests' && <em>12</em>}</button>)}</nav><div className="nav-bottom"><button><Settings size={18}/>Settings</button><button><CircleHelp size={18}/>Help & support</button><div className="profile"><div className="avatar purple">JD</div><div><b>Jordan Davis</b><small>Administrator</small></div><MoreHorizontal size={18}/></div></div></aside>
    <main><header><button className="menu" onClick={() => setSidebar(true)}><Menu /></button><div><p>Good morning, Jordan</p><h1>{active === 'Overview' ? 'Here’s what’s happening today.' : active}</h1></div><div className="header-actions"><button className="icon-button"><Bell size={19}/><i/></button><button className="new-request" onClick={() => setShowCreate(true)}><Plus size={18}/>New request</button></div></header>
      <section className="metrics"><Metric icon={<TicketCheck/>} name="Open requests" value={String(tickets.filter(t => t.status !== 'Resolved').length)} detail="↗ 8.2% from last week" tone="blue"/><Metric icon={<Clock3/>} name="Avg. response time" value="24m" detail="↘ 12% faster this month" tone="violet"/><Metric icon={<ShieldCheck/>} name="SLA compliance" value="98.4%" detail="↗ 2.1% from last month" tone="green"/><Metric icon={<Users/>} name="Active customers" value="248" detail="↗ 14 new this month" tone="orange"/></section>
      <section className="content-grid"><div className="panel requests"><div className="panel-head"><div><h2>Service requests</h2><p>Track and manage incoming requests</p></div><button className="text-button" onClick={() => setActive('Service requests')}>View all <span>→</span></button></div><div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search requests..."/></div><button className="filter"><SlidersHorizontal size={16}/>Filters</button></div><div className="table-wrap"><table><thead><tr><th>REQUEST</th><th>CUSTOMER</th><th>PRIORITY</th><th>STATUS</th><th>ASSIGNEE</th><th>UPDATED</th><th/></tr></thead><tbody>{visible.map(t => <tr key={t.id}><td><b>{t.id}</b><span>{t.title}</span></td><td>{t.customer}</td><td><Badge value={t.priority}/></td><td><Badge value={t.status}/></td><td><div className="assignee"><div className="avatar tiny">{t.assignee === 'Unassigned' ? '?' : t.assignee.split(' ').map(x=>x[0]).join('')}</div>{t.assignee}</div></td><td className="muted">{t.updated}</td><td><button className="dots"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div></div>
      <div className="right-column"><div className="panel activity"><div className="panel-head"><div><h2>Team activity</h2><p>Latest updates from your team</p></div><button className="dots"><MoreHorizontal size={18}/></button></div><Activity initials="AH" text={<><b>Amelia Harper</b> resolved <strong>SR-1045</strong></>} time="12 minutes ago" color="purple"/><Activity initials="DK" text={<><b>Daniel Kim</b> was assigned to <strong>SR-1047</strong></>} time="35 minutes ago" color="blue"/><Activity initials="JD" text={<><b>Jordan Davis</b> created <strong>SR-1048</strong></>} time="1 hour ago" color="orange"/><button className="activity-more">View all activity →</button></div><div className="panel workload"><div className="panel-head"><div><h2>Team workload</h2><p>Open requests by agent</p></div></div>{[['Amelia Harper', 8, 'purple'], ['Daniel Kim', 6, 'blue'], ['Priya Shah', 4, 'green']].map(([name, n, c]) => <div className="work" key={name as string}><div className={`avatar tiny ${c}`}>{(name as string).split(' ').map(x=>x[0]).join('')}</div><span>{name}</span><div className="bar"><i style={{width: `${Number(n)*10}%`}}/></div><b>{n}</b></div>)}</div></div></section>
    </main>{showCreate && <div className="modal-backdrop"><form className="modal" onSubmit={e => { e.preventDefault(); addTicket(e.currentTarget) }}><button type="button" className="modal-x" onClick={() => setShowCreate(false)}><X size={20}/></button><h2>Create service request</h2><p>Give your team the details they need to get started.</p><label>Request title<input name="title" autoFocus placeholder="e.g. VPN access not working"/></label><label>Customer<input name="customer" placeholder="Customer organization"/></label><label>Category<select name="category"><option>IT Support</option><option>Facilities</option><option>Billing</option><option>Onboarding</option></select></label><div className="modal-actions"><button type="button" onClick={() => setShowCreate(false)}>Cancel</button><button className="new-request" type="submit">Create request</button></div></form></div>}</div>;
}
function Metric({ icon, name, value, detail, tone }: {icon: React.ReactNode; name:string; value:string; detail:string; tone:string}) { return <article className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><div><p>{name}</p><h2>{value}</h2><small className={detail.includes('↘') ? 'good' : ''}>{detail}</small></div></article> }
function Activity({ initials, text, time, color }: { initials:string; text:React.ReactNode; time:string; color:string }) { return <div className="activity-row"><div className={`avatar ${color}`}>{initials}</div><div><p>{text}</p><small>{time}</small></div></div> }
export default App;
import { createRoot } from 'react-dom/client'; createRoot(document.getElementById('root')!).render(<App />);
